name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install sphinx sphinx-rtd-theme
          pip install -e .

      - name: Build Sphinx documentation
        run: |
          cd docs
          make clean
          make html
          
      - name: Deploy to GitHub Pages
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html/
          force_orphan: true

# references: 
# - https://coderefinery.github.io/documentation/gh_workflow/
# - https://github.com/marketplace/actions/sphinx-to-github-pages
